### ISSUE TITLE
"error" shows up on inputting api key

### ISSUE THREAD

**Issue by mohsin250999** [sunilkumardash9/Pdf-GPT#2]
Hey sunil,

Do you know what the issue with this is now? I've been trying to figure it out since yesterday and dont know why it stopped working

**Comment by sunilkumardash9** [comment]
Can you share the full error? I haven't updated anything in the code, shouldn't be showing an error.

**Comment by mohsin250999** [comment]
<img width="1280" alt="image" src="https://github.com/sunilkumardash9/Pdf-GPT/assets/43788631/6beb2e4f-0f8c-4448-8a94-cff830593589">
it just throws this error.


```
To create a public link, set `share=True` in `launch()`.
This is here
Traceback (most recent call last):
  File "C:\Users\mohsin\anaconda3\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\mohsin\anaconda3\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\mohsin\anaconda3\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\mohsin\anaconda3\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\mohsin\anaconda3\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\mohsin\anaconda3\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mohsin\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\mohsin\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\mohsin\anaconda3\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "c:/Users/mohsin/Desktop/Ricoh/Intern project/test/app.py", line 86, in get_response
    chain = app(file)
  File "c:/Users/mohsin/Desktop/Ricoh/Intern project/test/app.py", line 47, in __call__
    self.build_chain(file)
  File "c:/Users/mohsin/Desktop/Ricoh/Intern project/test/app.py", line 70, in build_chain
    documents, file_name = self.process_file(file)
  File "c:/Users/mohsin/Desktop/Ricoh/Intern project/test/app.py", line 66, in process_file
    file_name = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by sunilkumardash9** [comment]
Could you run it locally, and see if there is any problem? It wasn't meant to run on HF space where multiple people can access it. It needs a bit of refactoring for that. Feel free to fork and make changes.

**Comment by mohsin250999** [comment]
Nope locally it was giving the same error, i built it from scratch using your websites blog (which was very helpful, thanks!) and after making a few changes it seems to work .

**Comment by sunilkumardash9** [comment]
Yes, thanks for pointing that out. Missed a step.

**Comment by AIOpen123** [comment]
what was the fix?

**Comment by sunilkumardash9** [comment]
@AIOpen123 As far as I remember self.chain = self.build_chain(file) in __call__() was missed
